# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/interact/proto/main_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'app/interact/proto/main_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%app/interact/proto/main_service.proto\x12\x0einteract_proto\"O\n\x0fRegisterRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x19\n\x11registration_date\x18\x03 \x01(\t\"E\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0f\n\x07message\x18\x03 \x01(\t\"4\n\x10PostEventRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\"5\n\x11PostEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"C\n\x0e\x43ommentRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\"3\n\x0f\x43ommentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"F\n\x12GetCommentsRequest\x12\x0f\n\x07post_id\x18\x01 \x01(\x05\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x11\n\tpage_size\x18\x03 \x01(\x05\"U\n\x13GetCommentsResponse\x12)\n\x08\x63omments\x18\x01 \x03(\x0b\x32\x17.interact_proto.Comment\x12\x13\n\x0b\x63omment_cnt\x18\x02 \x01(\x05\"R\n\x07\x43omment\x12\x12\n\ncomment_id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\t2\xb4\x03\n\x0bMainService\x12S\n\x0cRegisterUser\x12\x1f.interact_proto.RegisterRequest\x1a .interact_proto.RegisterResponse\"\x00\x12Q\n\x08ViewPost\x12 .interact_proto.PostEventRequest\x1a!.interact_proto.PostEventResponse\"\x00\x12Q\n\x08LikePost\x12 .interact_proto.PostEventRequest\x1a!.interact_proto.PostEventResponse\"\x00\x12P\n\x0b\x43ommentPost\x12\x1e.interact_proto.CommentRequest\x1a\x1f.interact_proto.CommentResponse\"\x00\x12X\n\x0bGetComments\x12\".interact_proto.GetCommentsRequest\x1a#.interact_proto.GetCommentsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.interact.proto.main_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=57
  _globals['_REGISTERREQUEST']._serialized_end=136
  _globals['_REGISTERRESPONSE']._serialized_start=138
  _globals['_REGISTERRESPONSE']._serialized_end=207
  _globals['_POSTEVENTREQUEST']._serialized_start=209
  _globals['_POSTEVENTREQUEST']._serialized_end=261
  _globals['_POSTEVENTRESPONSE']._serialized_start=263
  _globals['_POSTEVENTRESPONSE']._serialized_end=316
  _globals['_COMMENTREQUEST']._serialized_start=318
  _globals['_COMMENTREQUEST']._serialized_end=385
  _globals['_COMMENTRESPONSE']._serialized_start=387
  _globals['_COMMENTRESPONSE']._serialized_end=438
  _globals['_GETCOMMENTSREQUEST']._serialized_start=440
  _globals['_GETCOMMENTSREQUEST']._serialized_end=510
  _globals['_GETCOMMENTSRESPONSE']._serialized_start=512
  _globals['_GETCOMMENTSRESPONSE']._serialized_end=597
  _globals['_COMMENT']._serialized_start=599
  _globals['_COMMENT']._serialized_end=681
  _globals['_MAINSERVICE']._serialized_start=684
  _globals['_MAINSERVICE']._serialized_end=1120
# @@protoc_insertion_point(module_scope)
