# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.interact.proto import main_service_pb2 as app_dot_interact_dot_proto_dot_main__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app/interact/proto/main_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterUser = channel.unary_unary(
                '/interact_proto.MainService/RegisterUser',
                request_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.RegisterRequest.SerializeToString,
                response_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.RegisterResponse.FromString,
                _registered_method=True)
        self.ViewPost = channel.unary_unary(
                '/interact_proto.MainService/ViewPost',
                request_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.SerializeToString,
                response_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.FromString,
                _registered_method=True)
        self.LikePost = channel.unary_unary(
                '/interact_proto.MainService/LikePost',
                request_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.SerializeToString,
                response_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.FromString,
                _registered_method=True)
        self.CommentPost = channel.unary_unary(
                '/interact_proto.MainService/CommentPost',
                request_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.CommentRequest.SerializeToString,
                response_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.CommentResponse.FromString,
                _registered_method=True)
        self.GetComments = channel.unary_unary(
                '/interact_proto.MainService/GetComments',
                request_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsRequest.SerializeToString,
                response_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsResponse.FromString,
                _registered_method=True)


class MainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LikePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommentPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetComments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterUser': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterUser,
                    request_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.RegisterRequest.FromString,
                    response_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.RegisterResponse.SerializeToString,
            ),
            'ViewPost': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewPost,
                    request_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.FromString,
                    response_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.SerializeToString,
            ),
            'LikePost': grpc.unary_unary_rpc_method_handler(
                    servicer.LikePost,
                    request_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.FromString,
                    response_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.SerializeToString,
            ),
            'CommentPost': grpc.unary_unary_rpc_method_handler(
                    servicer.CommentPost,
                    request_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.CommentRequest.FromString,
                    response_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.CommentResponse.SerializeToString,
            ),
            'GetComments': grpc.unary_unary_rpc_method_handler(
                    servicer.GetComments,
                    request_deserializer=app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsRequest.FromString,
                    response_serializer=app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interact_proto.MainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interact_proto.MainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interact_proto.MainService/RegisterUser',
            app_dot_interact_dot_proto_dot_main__service__pb2.RegisterRequest.SerializeToString,
            app_dot_interact_dot_proto_dot_main__service__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interact_proto.MainService/ViewPost',
            app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.SerializeToString,
            app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LikePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interact_proto.MainService/LikePost',
            app_dot_interact_dot_proto_dot_main__service__pb2.PostEventRequest.SerializeToString,
            app_dot_interact_dot_proto_dot_main__service__pb2.PostEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommentPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interact_proto.MainService/CommentPost',
            app_dot_interact_dot_proto_dot_main__service__pb2.CommentRequest.SerializeToString,
            app_dot_interact_dot_proto_dot_main__service__pb2.CommentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetComments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interact_proto.MainService/GetComments',
            app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsRequest.SerializeToString,
            app_dot_interact_dot_proto_dot_main__service__pb2.GetCommentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
