"""no majors

Revision ID: 7c4732e1b6cf
Revises: 29872123eee1
Create Date: 2025-03-07 22:12:11.279489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c4732e1b6cf'
down_revision: Union[str, None] = '29872123eee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_major_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'course')
    op.drop_column('users', 'address')
    op.drop_column('users', 'enrollment_year')
    op.drop_column('users', 'major_id')
    op.drop_column('users', 'special_notes')
    op.drop_table('majors')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('special_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('major_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('enrollment_year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('course', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('users_major_id_fkey', 'users', 'majors', ['major_id'], ['id'])
    op.create_table('majors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('major_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('major_description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('count_students', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='majors_pkey'),
    sa.UniqueConstraint('major_name', name='majors_major_name_key')
    )
    # ### end Alembic commands ###
