"""fix names

Revision ID: 5bb433f92582
Revises: 5bfc6bba3a0e
Create Date: 2025-03-07 20:49:45.902552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb433f92582'
down_revision: Union[str, None] = '5bfc6bba3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majors', sa.Column('count_users', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_column('majors', 'count_students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('majors', sa.Column('count_students', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_column('majors', 'count_users')
    # ### end Alembic commands ###
